# Generated by Django 3.1.5 on 2021-02-11 14:47

from django.db import migrations, models
import leads.models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0009_auto_20210211_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followup',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=leads.models.handle_upload_follow_ups),
        ),
    ]
