# Generated by Django 3.1.5 on 2021-02-11 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0010_auto_20210211_1447'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followup',
            old_name='leads',
            new_name='lead',
        ),
    ]
